A taxa de evasão pode ser calculada a partir da quantidade de alunos ingressos e egressos, considerando a duração dos cursos. A fórmula básica é: Taxa de Evasão = (1 − (Número de Egressos / Número de Ingressos)) × 100

In [238]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

In [249]:
##Inicialmente preferi realizar o trabalho manual de importar os databases para o python mas vou evoluir o projeto para implemnetar automoção por API

##Egressos
e21 = 'https://dadosabertos.ufms.br/dataset/9eda7d71-bb81-46b4-8e3c-9161346b6ebc/resource/733b0bc8-c616-41e1-93b5-b912ff4038a9/download/siscad-lista-egressos-2021.csv'
e22 = 'https://dadosabertos.ufms.br/dataset/9eda7d71-bb81-46b4-8e3c-9161346b6ebc/resource/9aa9035a-cdd9-44e0-b8f1-cec1b692db5d/download/lista_de_egresso_2022.csv'
e23 = 'https://dadosabertos.ufms.br/dataset/9eda7d71-bb81-46b4-8e3c-9161346b6ebc/resource/f0f2d176-a5b3-483f-a535-a1ed32bd9f96/download/siscad-lista-egressos-2023.csv'
e24 = 'https://dadosabertos.ufms.br/dataset/9eda7d71-bb81-46b4-8e3c-9161346b6ebc/resource/ad513f7b-9a0b-4130-836b-726260b7ba6b/download/siscad-lista-egressos-2024.csv'
e25 = 'https://dadosabertos.ufms.br/dataset/9eda7d71-bb81-46b4-8e3c-9161346b6ebc/resource/41cb7797-802c-4d7b-9502-5a8529651bcb/download/siscad-lista-egressos-2025.csv'

##Ingressos
i21 = 'https://dadosabertos.ufms.br/dataset/c08666c6-01a5-488a-9ff4-d1539ee33d7d/resource/18a93b16-c49c-4107-9dae-fb4b8c6e4c59/download/siscad-qtd-ingressos-2021.csv'
i22 = 'https://dadosabertos.ufms.br/dataset/c08666c6-01a5-488a-9ff4-d1539ee33d7d/resource/37b68d73-4bba-4684-b27f-a624cff17d66/download/quantidade_ingresso_graduacao_2022.csv'
i23 = 'https://dadosabertos.ufms.br/dataset/c08666c6-01a5-488a-9ff4-d1539ee33d7d/resource/3eb22a3c-cc9b-4f2e-8aba-059a569b20da/download/siscad-qtd-ingressos-2023.csv'
i24 = 'https://dadosabertos.ufms.br/dataset/c08666c6-01a5-488a-9ff4-d1539ee33d7d/resource/808f08d2-0b15-4109-97e6-9eb7f8169948/download/siscad-qtd-ingressos-2024.csv'
i25 = 'https://dadosabertos.ufms.br/dataset/c08666c6-01a5-488a-9ff4-d1539ee33d7d/resource/59b5b6f1-fba7-43e8-8bfc-636bb4785f06/download/siscad-qtd-ingressos-2025.csv'
basei25 = pd.read_csv(i25)
basei24 = pd.read_csv(i24)
basei23 = pd.read_csv(i23)
basei22 = pd.read_csv(i22)
basei21 = pd.read_csv(i21)

ingres_tot = pd.concat([basei25,basei24,basei23,basei22,basei21], ignore_index=True)
                      
basee25 = pd.read_csv(e25)
basee24 = pd.read_csv(e24)
basee23 = pd.read_csv(e23)
basee22 = pd.read_csv(e22)
basee21 = pd.read_csv(e21)

egres_tot = pd.concat([basee25,basee24,basee23,basee22,basee21], ignore_index=True)

ingres_tot.head()

,ano,semestre,unidade,curso,qtd_ingressos
0,2025,1,AGEAD,Curso Superior de Tecnologia da Informação,512
1,2025,1,AGEAD,Curso Superior de Tecnologia de Ciência dos Dados,503
2,2025,1,AGEAD,Curso Superior de Tecnologia em Educação e Pro...,151
3,2025,1,AGEAD,Curso Superior de Tecnologia em Educação e Pro...,152
4,2025,1,AGEAD,Curso Superior de Tecnologia em Gestão Comercial,382

In [250]:
## idxmin e idxmax procura o id do minimo e do náximo
id_max = base25['qtd_ingressos'].idxmax()
print(base25.loc[[id_max]])

    ano  semestre unidade                                       curso  \
0  2025         1   AGEAD  Curso Superior de Tecnologia da Informação

   qtd_ingressos
0            512

In [251]:
## Aqui realizei a padronização da tabea de Egressos para poder juntar futuramente com a de Ingressos e manipular o cálculo da evasão
egress_trat = egres_tot.groupby(['ano', 'semestre', 'unidade', 'curso',])['nome'].count().reset_index(name='qtd_egressos')
print(egress_trat.head(10))
egress_trat

    ano  semestre unidade                                              curso  \
0  2021         1    CPAN                        Administração - Bacharelado
1  2021         1    CPAN                 CIÊNCIAS BIOLÓGICAS - LICENCIATURA
2  2021         1    CPAN                   CIÊNCIAS CONTÁBEIS - BACHARELADO
3  2021         1    CPAN                              Direito - Bacharelado
4  2021         1    CPAN                     Educação Física - Licenciatura
5  2021         1    CPAN                           Geografia - Licenciatura
6  2021         1    CPAN                            História - Licenciatura
7  2021         1    CPAN  LETRAS - LICENCIATURA - HABILITAÇÃO EM PORTUGU...
8  2021         1    CPAN  Letras - Licenciatura - Habilitação em Portugu...
9  2021         1    CPAN                          Matemática - Licenciatura

   qtd_egressos
0             8
1             4
2             2
3            11
4             2
5             1
6             1
7             5
8             1
9             7

,ano,semestre,unidade,curso,qtd_egressos
0,2021,1,CPAN,Administração - Bacharelado,8
1,2021,1,CPAN,CIÊNCIAS BIOLÓGICAS - LICENCIATURA,4
2,2021,1,CPAN,CIÊNCIAS CONTÁBEIS - BACHARELADO,2
3,2021,1,CPAN,Direito - Bacharelado,11
4,2021,1,CPAN,Educação Física - Licenciatura,2
...,...,...,...,...,...
1010,2025,2,INFI,Física - Bacharelado,2
1011,2025,2,INISA,Enfermagem,39
1012,2025,2,INISA,Fisioterapia,27
1013,2025,2,INMA,Matemática - Licenciatura,1
1014,2025,2,INQUI,Química - Bacharelado em Química Tecnológica,2

In [253]:
# 1. Faz o merge trazendo apenas a chave de junção e a nova coluna desejada
df_geral = pd.merge(
    ingres_tot,
    egress_trat[['ano', 'semestre', 'unidade', 'curso', 'qtd_egressos']], # Seleciona só a chave + a coluna nova do df2 que é qtd_egressos
    on= ['ano', 'semestre', 'unidade', 'curso'],              # Coluna que serve de chave em ambos
    how='left'                                                # Mantém todas as linhas de df1
)

In [254]:
df_geral

,ano,semestre,unidade,curso,qtd_ingressos,qtd_egressos
0,2025,1,AGEAD,Curso Superior de Tecnologia da Informação,512,110.0
1,2025,1,AGEAD,Curso Superior de Tecnologia de Ciência dos Dados,503,79.0
2,2025,1,AGEAD,Curso Superior de Tecnologia em Educação e Pro...,151,NaN
3,2025,1,AGEAD,Curso Superior de Tecnologia em Educação e Pro...,152,NaN
4,2025,1,AGEAD,Curso Superior de Tecnologia em Gestão Comercial,382,22.0
...,...,...,...,...,...,...
978,2021,2,INQUI,Engenharia Química - Bacharelado,3,NaN
979,2021,2,INQUI,Química - Bacharelado em Química Tecnológica,5,14.0
980,2021,2,INQUI,Química - Licenciatura,1,2.0
981,2021,2,UFMS,ALUNO ESPECIAL,4,NaN
982,2021,2,UFMS,MOBILIDADE ACADÊMICA,5,NaN

In [280]:
##(1 − (Número de Egressos / Número de Ingressos)) × 100
df_geral['evasao'] = (1 - (df_geral['qtd_egressos']  / df_geral['qtd_ingressos'])) * 100
df_geral['evasao'] = df_geral['evasao'].round(2) ## round(1) arredondando as casas decimais

In [281]:
##Sem evasão
sem_evasao = df_geral[df_geral.isnull().any(axis=1)]
sem_evasao

,ano,semestre,unidade,curso,qtd_ingressos,qtd_egressos,evasao
2,2025,1,AGEAD,Curso Superior de Tecnologia em Educação e Pro...,151,NaN,NaN
3,2025,1,AGEAD,Curso Superior de Tecnologia em Educação e Pro...,152,NaN,NaN
9,2025,1,AGEAD,História,486,NaN,NaN
10,2025,1,AGEAD,Letras Português e Espanhol,213,NaN,NaN
11,2025,1,AGEAD,Pedagogia,217,NaN,NaN
...,...,...,...,...,...,...,...
973,2021,2,INFI,Engenharia Física - Bacharelado,5,NaN,NaN
976,2021,2,INMA,Matemática - Bacharelado,4,NaN,NaN
978,2021,2,INQUI,Engenharia Química - Bacharelado,3,NaN,NaN
981,2021,2,UFMS,ALUNO ESPECIAL,4,NaN,NaN
982,2021,2,UFMS,MOBILIDADE ACADÊMICA,5,NaN,NaN

In [282]:
## Apenas com evasao
com_evasao = pd.concat([df_geral, sem_evasao, sem_evasao]).drop_duplicates(keep=False)
com_evasao['qtd_egressos'] = com_evasao['qtd_egressos'].astype(np.int64)
com_evasao

,ano,semestre,unidade,curso,qtd_ingressos,qtd_egressos,evasao
0,2025,1,AGEAD,Curso Superior de Tecnologia da Informação,512,110,78.52
1,2025,1,AGEAD,Curso Superior de Tecnologia de Ciência dos Dados,503,79,84.29
4,2025,1,AGEAD,Curso Superior de Tecnologia em Gestão Comercial,382,22,94.24
5,2025,1,AGEAD,Curso Superior de Tecnologia em Gestão de Mídi...,204,16,92.16
6,2025,1,AGEAD,Curso Superior de Tecnologia em Gestão de Recu...,407,50,87.71
...,...,...,...,...,...,...,...
974,2021,2,INFI,Física - Licenciatura,1,2,-100.00
975,2021,2,INISA,Fisioterapia - Bacharelado,1,23,-2200.00
977,2021,2,INMA,Matemática - Licenciatura,1,21,-2000.00
979,2021,2,INQUI,Química - Bacharelado em Química Tecnológica,5,14,-180.00
980,2021,2,INQUI,Química - Licenciatura,1,2,-100.00

In [262]:
## Esses anos sem evasão do curso significa que ele tinha acadado de ser iniciado, então não tinha tempo de ter formados.
sem_evasao[sem_evasao['curso'] == 'Curso Superior de Tecnologia de Ciência dos Dados']

,ano,semestre,unidade,curso,qtd_ingressos,qtd_egressos,evasao
188,2024,1,AGEAD,Curso Superior de Tecnologia de Ciência dos Dados,723,NaN,NaN
313,2024,2,AGEAD,Curso Superior de Tecnologia de Ciência dos Dados,1,NaN,NaN
382,2023,1,AGEAD,Curso Superior de Tecnologia de Ciência dos Dados,517,NaN,NaN
512,2023,2,AGEAD,Curso Superior de Tecnologia de Ciência dos Dados,48,NaN,NaN
755,2022,2,AGEAD,Curso Superior de Tecnologia de Ciência dos Dados,563,NaN,NaN

In [284]:
##Procurei apenas os dados dos cursos da AGEAD em todo o periodo
cursos_ead = df_geral[df_geral['unidade'] == 'AGEAD']
cursos_ead

,ano,semestre,unidade,curso,qtd_ingressos,qtd_egressos,evasao
0,2025,1,AGEAD,Curso Superior de Tecnologia da Informação,512,110.0,78.52
1,2025,1,AGEAD,Curso Superior de Tecnologia de Ciência dos Dados,503,79.0,84.29
2,2025,1,AGEAD,Curso Superior de Tecnologia em Educação e Pro...,151,NaN,NaN
3,2025,1,AGEAD,Curso Superior de Tecnologia em Educação e Pro...,152,NaN,NaN
4,2025,1,AGEAD,Curso Superior de Tecnologia em Gestão Comercial,382,22.0,94.24
5,2025,1,AGEAD,Curso Superior de Tecnologia em Gestão de Mídi...,204,16.0,92.16
6,2025,1,AGEAD,Curso Superior de Tecnologia em Gestão de Recu...,407,50.0,87.71
7,2025,1,AGEAD,Curso Superior de Tecnologia em Gestão de Serv...,296,33.0,88.85
8,2025,1,AGEAD,Curso Superior de Tecnologia em Processos Gere...,295,70.0,76.27
9,2025,1,AGEAD,História,486,NaN,NaN
10,2025,1,AGEAD,Letras Português e Espanhol,213,NaN,NaN
11,2025,1,AGEAD,Pedagogia,217,NaN,NaN
129,2025,2,AGEAD,Curso Superior de Tecnologia em Gestão de Mídi...,14,44.0,-214.29
130,2025,2,AGEAD,História,163,NaN,NaN
131,2025,2,AGEAD,Letras Português e Espanhol,10,NaN,NaN
187,2024,1,AGEAD,Curso Superior de Tecnologia da Informação,537,NaN,NaN
188,2024,1,AGEAD,Curso Superior de Tecnologia de Ciência dos Dados,723,NaN,NaN
189,2024,1,AGEAD,Curso Superior de Tecnologia em Gestão Comercial,305,NaN,NaN
190,2024,1,AGEAD,Curso Superior de Tecnologia em Gestão de Mídi...,346,NaN,NaN
191,2024,1,AGEAD,Curso Superior de Tecnologia em Gestão de Recu...,512,NaN,NaN
192,2024,1,AGEAD,Curso Superior de Tecnologia em Gestão de Serv...,337,NaN,NaN
193,2024,1,AGEAD,História - Licenciatura,308,NaN,NaN
194,2024,1,AGEAD,Letras Português e Espanhol,326,NaN,NaN
195,2024,1,AGEAD,Pedagogia,553,NaN,NaN
196,2024,1,AGEAD,Tecnologia em Processos Gerenciais,373,179.0,52.01
312,2024,2,AGEAD,Curso Superior de Tecnologia da Informação,1,NaN,NaN
313,2024,2,AGEAD,Curso Superior de Tecnologia de Ciência dos Dados,1,NaN,NaN
314,2024,2,AGEAD,Curso Superior de Tecnologia em Gestão Comercial,44,9.0,79.55
315,2024,2,AGEAD,História - Licenciatura,69,NaN,NaN
316,2024,2,AGEAD,Letras Português e Espanhol,52,NaN,NaN
381,2023,1,AGEAD,Curso Superior de Tecnologia da Informação,635,NaN,NaN
382,2023,1,AGEAD,Curso Superior de Tecnologia de Ciência dos Dados,517,NaN,NaN
383,2023,1,AGEAD,Curso Superior de Tecnologia em Gestão Comercial,203,NaN,NaN
384,2023,1,AGEAD,Curso Superior de Tecnologia em Gestão de Míd...,266,NaN,NaN
385,2023,1,AGEAD,Curso Superior de Tecnologia em Gestão de Recu...,338,NaN,NaN
386,2023,1,AGEAD,Curso Superior de Tecnologia em Gestão de Ser...,259,NaN,NaN
387,2023,1,AGEAD,Curso Superior de Tecnologia em Processos Gere...,297,NaN,NaN
388,2023,1,AGEAD,História,303,NaN,NaN
389,2023,1,AGEAD,Letras Português e Espanhol,305,NaN,NaN
390,2023,1,AGEAD,Pedagogia,418,NaN,NaN
511,2023,2,AGEAD,Curso Superior de Tecnologia da Informação,42,NaN,NaN
512,2023,2,AGEAD,Curso Superior de Tecnologia de Ciência dos Dados,48,NaN,NaN
513,2023,2,AGEAD,Curso Superior de Tecnologia em Gestão Comercial,13,NaN,NaN
514,2023,2,AGEAD,Curso Superior de Tecnologia em Gestão de Míd...,51,NaN,NaN
515,2023,2,AGEAD,Curso Superior de Tecnologia em Gestão de Recu...,46,NaN,NaN
516,2023,2,AGEAD,Curso Superior de Tecnologia em Gestão de Ser...,40,NaN,NaN
517,2023,2,AGEAD,Curso Superior de Tecnologia em Processos Gere...,44,NaN,NaN
518,2023,2,AGEAD,História,26,NaN,NaN
519,2023,2,AGEAD,Letras Português e Espanhol,21,NaN,NaN
520,2023,2,AGEAD,Pedagogia,34,NaN,NaN
592,2022,1,AGEAD,Ciências Interdisciplinar,70,NaN,NaN
593,2022,1,AGEAD,Letras Português,71,NaN,NaN
594,2022,1,AGEAD,Matemática,39,NaN,NaN
595,2022,1,AGEAD,Pedagogia,76,NaN,NaN
754,2022,2,AGEAD,Curso Superior de Tecnologia da Informação,760,NaN,NaN
755,2022,2,AGEAD,Curso Superior de Tecnologia de Ciência dos Dados,563,NaN,NaN
756,2022,2,AGEAD,Curso Superior de Tecnologia em Processos Gere...,713,NaN,NaN